# Generated by Django 2.2.16 on 2022-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20220803_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='media/CHIN.jpg', upload_to='media/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
