# Generated by Django 2.2.16 on 2022-08-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20220808_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipeamount',
            options={'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
    ]
